[encryption]
DEFAULT_ADMIN_PASSWORD = "password"
DEFAULT_ADMIN_USERNAME = "admin"
DEFAULT_ADMIN_EMAIL = "citlab@lanecc.edu"
SECRET_KEY = "tgh45y4566y45y7fyhj66"
SESSION_COOKIE_SECURE = true
SESSION_COOKIE_NAME = "UsageTracker_Cookie"

[smtp]
ACCOUNT = "myapp"
SUPPORT_EMAIL = "citlab@lanecc.edu"
EMAIL_FILE_PATH = "/tmp/email.txt"

[flask]
SQLALCHEMY_DATABASE_URI = "sqlite:///attendance.db"
DEBUG = false

[sshfs]
REMOTE_TSV_PATH = "/data/"
HOST = "nlms.lanecc.edu"
USER = "app"
PORT = 22
PRIVATE_KEY_PATH = "app_keys/id_rsa"
LOCAL_STUDENT_FILE = "zsrsinf_cit.txt"
