[encryption]
DEFAULT_ADMIN_PASSWORD = "p"
DEFAULT_ADMIN_USERNAME = "a"
DEFAULT_ADMIN_EMAIL = "pass@a.edu"
SECRET_KEY = "hashedkeyhashedkeyhashedkey"
SESSION_COOKIE_SECURE = false
SESSION_COOKIE_NAME = "sdgsd"

[smtp]
ACCOUNT = "myapp"
SUPPORT_EMAIL = "rosenauj@my.lanecc.edu"

[flask]
SQLALCHEMY_DATABASE_URI = "sqlite:///attendance.db"
DEBUG = true

[sshfs]
REMOTE_TSV_PATH = "/data/"
HOST = "nlms.lanecc.edu"
USER = "app"
PORT = 22
PRIVATE_KEY_PATH = "app_keys/id_rsa"