[encryption]
VALID_EMAILS = "rosenauj@my.lanecc.edu"  # Add valid emails here

[smtp]
ACCOUNT = "myapp"
SUPPORT_EMAIL = "rosenauj@my.lanecc.edu"

[flask]
SQLALCHEMY_DATABASE_URI = "sqlite:///attendance.db"
DEBUG = true

